- name: Gabe's playbook
  hosts: localhost
  gather_facts: True

  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      when: ansible_facts['os_family'] == 'Debian'

  tasks:
    - name: macOS tasks
      import_tasks: tasks/setup/mac.yaml
      when: ansible_facts['os_family'] == 'Darwin'

    - name: debian tasks
      import_tasks: tasks/setup/debian.yaml
      when: ansible_facts['os_family'] == 'Debian'
